---
name: go-web Extended Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

permissions:
  contents: read
  id-token: write

jobs:
  get-latest-version:
    uses: coreeng/p2p/.github/workflows/p2p-get-latest-image-extended-test.yaml@v1
    secrets:
      slack_webhook_url: ${{ secrets.P2P_SLACK_WEBHOOK_URL }}
    with:
      image-name: go-web
      tenant-name: $(TENANT_NAME)

  extendedtests:
    needs: [get-latest-version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-extended-test.yaml@v1
    secrets:
      slack_webhook_url: ${{ secrets.P2P_SLACK_WEBHOOK_URL }}
      env_vars: ${{ secrets.env_vars }}
    with:
      app-name: go-web
      tenant-name: $(TENANT_NAME)
      version: ${{ needs.get-latest-version.outputs.version }}
      version-prefix: v
      working-directory: ./
