registry:

functional:
  image: java-web-functional:latest
nft:
  image: java-web-nft:latest
service:
  image: java-web:latest
  environmentVariables:
    POSTGRES_HOST: reference-db-service
    DOWNSTREAM_HOST: reference-podinfo-service

