name: Fast Feedback

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref'
        type: string
        required: false
        default: ''
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@multiapp-fixes
    with:
      # TODO replace with main
      main-branch: 'refs/heads/workflow-dev'
      checkout-version: ${{ inputs.ref }}
      version-prefix: '${{ inputs.lifecycle }}/v'
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}

  log:
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Ref: '${{ github.ref }}'"
          echo "RefType: '${{ github.ref_type }}'"

  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@multiapp-fixes
    with:
      main-branch: 'refs/heads/workflow-dev'
      checkout-version: ${{ inputs.ref }}
      working-directory: './${{ inputs.lifecycle }}'
      version: ${{ needs.version.outputs.version }}