name: Fast Feedback

on:
  workflow_call:
    inputs:
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    with:
      # TODO replace with main
      main-branch: 'workflow-dev'
      version-prefix: '${{ inputs.lifecycle }}/v'
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}

  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@v1
    with:
      main-branch: 'workflow-dev'
      working-directory: './${{ inputs.lifecycle }}'
#      version: 'v0.0.1'
      version: ${{ needs.version.outputs.version }}