name: Extended tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  find-lifecycles:
    uses: ./.github/workflows/find-lifecycles.yaml
  extended-tests:
    needs: [find-lifecycles]
    uses: ./.github/workflows/extended-test.yaml
    if: needs.detect-changed-lifecycles.outputs.changed-lifecycles!= '[]'
    strategy:
      matrix:
        lifecycle: ${{ fromJSON(needs.find-lifecycles.outputs.lifecycles) }}
    continue-on-error: true
    with:
      lifecycle: ${{ matrix.lifecycle }}