name: P2P
on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref'
        type: string
        required: false
        default: ''
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@multiapp-fixes
    with:
      # TODO replace with main
      main-branch: 'refs/heads/workflow-dev'
      checkout-version: ${{ inputs.ref }}
      version-prefix: '${{ inputs.lifecycle }}/v'
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@multiapp-fixes
    with:
      main-branch: 'refs/heads/workflow-dev'
      working-directory: './${{ inputs.lifecycle }}'
      checkout-version: ${{ inputs.ref }}
      version: ${{ needs.version.outputs.version }}
  extendedtests:
    needs: [fastfeedback, version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-extended-test.yaml@multiapp-fixes
    with:
      main-branch: 'refs/heads/workflow-dev'
      working-directory: './${{ inputs.lifecycle }}'
      version: ${{ needs.version.outputs.version }}
      version-prefix: '${{ inputs.lifecycle }}/v'
  prod:
    needs: [extendedtests, version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-prod.yaml@multiapp-fixes
    with:
      main-branch: 'refs/heads/workflow-dev'
      working-directory: './${{ inputs.lifecycle }}'
      version: ${{ needs.version.outputs.version }}
      version-prefix: '${{ inputs.lifecycle }}/v'
  failure-alert:
    needs: [version, fastfeedback, extendedtests, prod]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_ALERT_URL }}
        with:
          payload: |
            {
              "notification": "❌ P2P for '${{ inputs.lifecycle }}' is failed!",
              "workflow_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
