name: P2P
on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref'
        type: string
        required: false
        default: ''
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@multiapp-fixes
    with:
      # TODO replace with main
      main-branch: 'refs/heads/workflow-dev'
      checkout-version: ${{ inputs.ref }}
      version-prefix: '${{ inputs.lifecycle }}/v'
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@multiapp-fixes
    with:
      main-branch: 'refs/heads/workflow-dev'
      checkout-version: ${{ inputs.ref }}
      working-directory: './${{ inputs.lifecycle }}'
      version: ${{ needs.version.outputs.version }}
  extendedtests:
    needs: [fastfeedback]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-extended-test.yaml@multiapp-fixes
    with:
      version: ${{ needs.version.outputs.version }}
  prod:
    needs: [extendedtests]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-prod.yaml@multiapp-fixes
    with:
      version: ${{ needs.version.outputs.version }}


#  fast-feedback:
#    uses: ./.github/workflows/fast-feedback.yaml
#    with:
#      lifecycle: ${{ inputs.lifecycle }}
#      ref: ${{ inputs.ref }}
#  extended-tests:
#    needs: [fast-feedback]
#    uses: ./.github/workflows/extended-test.yaml
#    with:
#      lifecycle: ${{ inputs.lifecycle }}
#  prod:
#    needs: [extended-tests]
#    uses: ./.github/workflows/prod.yaml
#    with:
#      lifecycle: ${{ inputs.lifecycle }}

