name: Prod

on:
  workflow_call:
    inputs:
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  get-latest-version:
    uses: coreeng/p2p/.github/workflows/p2p-get-latest-image-prod.yaml@multiapp-fixes
    with:
      image-name: ${{ inputs.lifecycle }}

  prod:
    needs: [get-latest-version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-prod.yaml@multiapp-fixes
    with:
      version: ${{ needs.get-latest-version.outputs.version }}
