name: Prod

on:
  workflow_call:
    inputs:
      lifecycle:
        description: 'The lifecycle to run'
        type: string
        required: true
      image-name:
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  get-image-name:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.image_name }}
    steps:
      - uses: actions/checkout@v2
      - id: image-name
        env:
          MAKEFILE: ./${{ inputs.lifecycle }}/Makefile
        run: |
          image="$(make -f "$MAKEFILE" p2p-image)"
          echo "image_name=$image" >> $GITHUB_OUTPUT

  get-latest-version:
    needs: [get-image-name]
    uses: coreeng/p2p/.github/workflows/p2p-get-latest-image-prod.yaml@multiapp-fixes
    with:
      image-name: ${{ needs.get-image-name.outputs.image-name }}

  prod:
    needs: [get-latest-version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-prod.yaml@multiapp-fixes
    with:
      version: ${{ needs.get-latest-version.outputs.version }}
