---
name: reference-monitoring-stack Fast Feedback
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - reference-monitoring-stack/**
  pull_request:
    branches:
      - main
    paths:
      - reference-monitoring-stack/**
permissions:
  contents: write
  id-token: write
  pull-requests: write
jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    with:
      version-prefix: reference-monitoring-stack/v
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.P2P_SLACK_WEBHOOK_URL }}
  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@v1
    secrets:
      slack_webhook_url: ${{ secrets.P2P_SLACK_WEBHOOK_URL }}
      env_vars: ${{ secrets.env_vars }}
    with:
      app-name: reference-monitoring-stack
      tenant-name: reference-monitoring-stack
      version: ${{ needs.version.outputs.version }}
      working-directory: reference-monitoring-stack
