name: Render templates
on:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  render:
    runs-on: ubuntu-latest
    outputs:
      changed_templates: ${{ steps.render.outputs.changed_templates }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./reference-apps
          fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          repository: coreeng/software-templates
          path: ./software-templates
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: coreeng/corectl
          latest: true
          fileName: corectl_Linux_x86_64.tar.gz
          extract: true
          out-file-path: corectl
      - id: render
        run: |
          export PATH="${PATH}:$(realpath ./corectl)"
          all_templates=( $(corectl template list --templates ./software-templates) )
          changed_templates=()
          for t in ${all_templates[@]}; do
            echo "Rendering template \'$t\'"
            rm -rf "./reference-apps/$t"
            mkdir -p "./reference-apps/$t"
            corectl template render "$t" "./reference-apps/$t" --templates ./software-templates
            git -C "./reference-apps" add "./$t"
            if [[ -n "$(git -C './reference-apps' status './$t' --untracked-files=no --porcelain)" ]]; then
              echo "Template '$t' has changed!"
              changed_templates+=("$t")
            fi
          done
          echo "changed_templates=$(echo $changed_templates | jq -Rc 'split(" ")')" >> $GITHUB_OUTPUT
          git -C "./reference-apps" status --porcelain
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./reference-apps
          commit_message: "chore: update templates"
  test-deploy:
    runs-on: ubuntu-latest
    needs: [render]
    strategy:
      matrix:
        changed_template: ${{ needs.render.outputs.changed_templates }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Deploying template '${{ matrix.changed_template }}'"


