name: Render templates
on:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./reference-apps
          fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          repository: coreeng/software-templates
          path: ./software-templates
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: coreeng/corectl
          latest: true
          fileName: corectl_Linux_x86_64.tar.gz
          extract: true
          out-file-path: corectl
      - run: |
          export PATH="${PATH}:$(realpath ./corectl)"
          all_templates=( $(corectl template list --templates ./software-templates) )
          changed_templates=()
          for t in ${all_templates[@]}; do
            echo "Rendering template \'$t\'"
            rm -rf "./reference-apps/$t"
            mkdir -p "./reference-apps/$t"
            corectl template render "$t" "./reference-apps/$t" --templates ./software-templates
            git -C "./reference-apps" add "./$t"
          done
          
          git -C "./reference-apps" rev-parse --abbrev-ref HEAD
          git -C "./reference-apps" status
          if [ -z $(git -C "./reference-apps" status -u --porcelain) ]; then
            echo "No changes detected"
          else
            git -C "./reference-apps" commit -m "Update rendered templates"
            git -C "./reference-apps" push origin workflow-dev
          fi
