name: Render templates
on:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./reference-apps
          fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          repository: coreeng/software-templates
          path: ./software-templates
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: coreeng/corectl
          latest: true
          fileName: corectl_Linux_x86_64.tar.gz
          extract: true
          out-file-path: corectl
      - run: |
          export PATH="${PATH}:$(realpath ./corectl)"
          all_templates=( $(corectl template list --templates ./software-templates) )
          changed_templates=()
          for t in ${all_templates[@]}; do
            echo "Rendering template \'$t\'"
            rm -rf "./reference-apps/$t"
            mkdir -p "./reference-apps/$t"
            corectl template render "$t" "./reference-apps/$t" --templates ./software-templates
            git add "./$t" -C "./reference-apps"
          done
          
          git rev-parse --abbrev-ref HEAD -C "./reference-apps"
          git status -C "./reference-apps"
          if git diff --exit-code -C "./reference-apps"; then
            echo "No changes detected"
          else
            git commit -m "Update rendered templates" -C "./reference-apps"
            git push origin workflow-dev  -C "./reference-apps"
          fi
