on:
  push:
    branches:
      - workflow-dev

jobs:
  detect-changed-lifecycles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: find-lifecycles
        uses: ./.github/workflows/find-lifecycles.yaml
      - id: generate-scan-config
        env:
          LIFECYCLES: ${{ steps.find-lifecycles.outputs.lifecycles }}
        run: |
          files_yaml="$(echo "${LIFECYCLES[*]}" | jq 'map({(.): [(.) + "/**"]}) | add' | yq -P)')"
          echo "files_yaml=\n$files_yaml"
          
          echo 'files_yaml<<EOF' >> $GITHUB_OUTPUT
          echo '$files_yaml' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: ${{ steps.generate-scan-config.outputs.files_yaml }}
      - run: |
          echo "Result: '${{ steps.changed-files.outputs.modified_keys }}'"
