on:
  push:
    branches:
      - workflow-dev

jobs:
  find-lifecycles:
    uses: ./.github/workflows/find-lifecycles.yaml
  detect-changed-lifecycles:
    needs: [find-lifecycles]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate-scan-config
        env:
          LIFECYCLES: ${{ needs.find-lifecycles.outputs.lifecycles }}
        run: |
          files_yaml="$(echo "${LIFECYCLES[*]}" | jq 'map({(.): [(.) + "/**"]}) | add' | yq -P)"
          echo "files_yaml:"
          echo "$files_yaml"
          
          echo 'files_yaml<<EOF' >> $GITHUB_OUTPUT
          echo "$files_yaml" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
#            blank:
#              - blank/**
#            go-web:
#              - go-web/**
            ${{ steps.generate-scan-config.outputs.files_yaml }}
      - run: |
          echo "Result: '${{ steps.changed-files.outputs.modified_keys }}'"
